<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-V7U200JF" name="com.fuyoujiankang.test.testcases.serviceManagement.ComboPage_002_AddSuccessFunction_Test" tests="1" failures="1" timestamp="30 Nov 2017 06:17:31 GMT" time="0.208" errors="0">
  <testcase name="addSuccessFunction" time="0.208" classname="com.fuyoujiankang.test.testcases.serviceManagement.ComboPage_002_AddSuccessFunction_Test">
    <failure type="java.lang.AssertionError" message="输入 [18817715180] 到 元素[By.id: username]失败">
      <![CDATA[java.lang.AssertionError: 输入 [18817715180] 到 元素[By.id: username]失败
	at org.testng.Assert.fail(Assert.java:94)
	at com.fuyoujiankang.test.utils.SeleniumUtil.type(SeleniumUtil.java:168)
	at com.fuyoujiankang.test.pageshelper.LoginPageHelper.typeHospitalLoginInfo(LoginPageHelper.java:26)
	at com.fuyoujiankang.test.testcases.serviceManagement.ComboPage_002_AddSuccessFunction_Test.addSuccessFunction(ComboPage_002_AddSuccessFunction_Test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addSuccessFunction -->
</testsuite> <!-- com.fuyoujiankang.test.testcases.serviceManagement.ComboPage_002_AddSuccessFunction_Test -->
